### ISSUE TITLE
Can't get this installed in Blender

### ISSUE THREAD

**Issue by fisj** [Silvergust/MM-Linker#1]
I feel dumb, but for the life of me, I cannot seem to get this working in Blender. After installing, activating this by toggling the addon "active" doesn't work, it always remains inactive. Am I missing something silly?

![blenderaddon_02](https://user-images.githubusercontent.com/960037/215609055-bddc98de-9c69-43da-9432-81163c1b79c9.png)

Using Blender 3.4.1 but also tried 3.2

**Comment by fisj** [comment]
More info, here's what blender's log is saying:
```
addon not loaded: 'MM-Linker-master'
cause: cannot import name 'websockets' from partially initialized module 'MM-Linker-master' (most likely due to a circular import) (<redacted>\addons\MM-Linker-master\__init__.py)
```

**Comment by Silvergust** [comment]
You aren't missing anything, the problem is that the repository is missing a dependency (the websockets library), it was supposed to be in the release but apparently I never published it. You can now download it from [here](https://github.com/Silvergust/MM-Linker/releases/tag/Release).
I'll add a note in the description to that effect. Thank you for bringing this up.
